---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# mixedCCA: sparse CCA for data of mixed types

The R package `mixedCCA` implements sparse canonical correlation analysis for data of mixed types: continuous, binary or zero-inflated (truncated continuous). The corresponding reference is

["Sparse semiparametric canonical correlation analysis for data of mixed types" by Yoon, Carroll and Gaynanova](http://arxiv.org/abs/1807.05274) (2018+).


## Installation

```{install}
devtools::install_github("irinagain/mixedCCA")
```

## Example

```{r example, results="hide", message=FALSE}
library(mixedCCA)

# Data generation
set.seed(1)
n <- 100; p1 <- 5; p2 <- 7
maxcancor <- 0.9 # true canonical correlation
Sigma1 <- autocor(p1, 0.7)
blockind <- c(rep(1, 2), rep(2, p2-2))
Sigma2 <- blockcor(blockind, 0.7)
copula1 <- "exp"; copula2 <- "cube" # transformation for Gaussian copula model
mu <- rep(0, p1+p2)
type1 <- type2 <- "trunc" # X1: truncated continuous, X2: truncated continuous
c1 <- rep(0, p1); c2 <- rep(0, p2) # threshold for truncation of underlying continuous variable
trueidx1 <- c(0, 0, 1, 1, 1) # true variable indices for dataset X1
trueidx2 <- c(1, 0, 1, 0, 0, 1, 1) # true variable indices for dataset X2
simdata <- GenerateData(n=n, trueidx1 = trueidx1, trueidx2 = trueidx2, maxcancor = maxcancor,
                        Sigma1 = Sigma1, Sigma2 = Sigma2,
                        copula1 = copula1, copula2 = copula2,
                        muZ = mu,
                        type1 = type1, type2 = type2, c1 = c1, c2 = c2
)
X1 <- simdata$X1
X2 <- simdata$X2

# Sparse semiparametric CCA with BIC1 criterion
mixedCCAresult <- mixedCCA(X1, X2, type1 = "trunc", type2 = "trunc", BICtype = 1)
mixedCCAresult$KendallR # extracts estimated latent correlation matrix
mixedCCAresult$w1 # canonical vector for X1
mixedCCAresult$w2 # canonical vector for X2
mixedCCAresult$cor # canonical correlation

# Separate estimation of latent correlation matrix
estimateR(X1, type = "trunc") # For X1 only
estimateR_mixed(X1, X2, type1 = "trunc", type2 = "trunc") # For X = (X1, X2)
```
