// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lassobic
Rcpp::List lassobic(int n, const arma::mat& R1, const arma::colvec& d, arma::colvec w1init, const arma::colvec& lamseq, int BICtype, int maxiter, double tol, int lassoverbose);
RcppExport SEXP _mixedCCA_lassobic(SEXP nSEXP, SEXP R1SEXP, SEXP dSEXP, SEXP w1initSEXP, SEXP lamseqSEXP, SEXP BICtypeSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP lassoverboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R1(R1SEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type w1init(w1initSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type lamseq(lamseqSEXP);
    Rcpp::traits::input_parameter< int >::type BICtype(BICtypeSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type lassoverbose(lassoverboseSEXP);
    rcpp_result_gen = Rcpp::wrap(lassobic(n, R1, d, w1init, lamseq, BICtype, maxiter, tol, lassoverbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixedCCA_lassobic", (DL_FUNC) &_mixedCCA_lassobic, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixedCCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
