# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lassobic <- function(n, R1, d, w1init, lamseq, BICtype, maxiter = 1000L, tol = 0.0001, lassoverbose = 1L) {
    .Call(`_mixedCCA_lassobic`, n, R1, d, w1init, lamseq, BICtype, maxiter, tol, lassoverbose)
}

