# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_w12bic <- function(n, R1, R2, R12, lambda1, lambda2, w1init, w2init, BICtype, maxiter = 1000L, tol = 0.001, verbose = TRUE) {
    .Call('_mixedCCA_find_w12bic', PACKAGE = 'mixedCCA', n, R1, R2, R12, lambda1, lambda2, w1init, w2init, BICtype, maxiter, tol, verbose)
}

